db:
  image: kartoza/postgis:9.4-2.1
  container_name: gfdrr_oondra-geonode-db
  hostname: geonode-db
  volumes:
    - ./pg/postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker
  ports:
    - "6003:5432"

dbbackups:
  container_name: gfdrr_oondra-db-backup
  image: kartoza/pg-backup:9.4
  hostname: pg-backups
  volumes:
    - ./backups:/backups
  links:
    - db:db
  environment:
    - DUMPPREFIX=PG_gfdrr
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGPORT=5432
    - PGHOST=db
    - PGDATABASE=gis
  restart: on-failure:5

geonode:
  build: docker-geonode
  container_name: gfdrr_oondra-geonode
  hostname: geonode
  ports:
    - "8111:8000"
    - "8181:8080"
  environment:
    - DATABASE_NAME=gis
    - DATABASE_USERNAME=docker
    - DATABASE_PASSWORD=docker
    - DATABASE_HOST=db
  links:
    - db:db



